name: Indirect Matrix Example

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_output.outputs.matrix }}
    steps:
      - name: Set Output
        id: set_output
        run: |
          echo "matrix=["value1","value2","value3"]" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix: 
        param2: ${{ needs.job1.outputs.matrix }}
    steps:
      - name: Print Matrix
        run: |
          echo "Matrix values: ${{ matrix.param2 }}"