name: Indirect Matrix Example

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_output.outputs.matrix }}
    steps:
      - name: Set Output
        id: set_output
        run: echo "::set-output name=matrix::value1,value2,value3"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param2: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
      - name: Print Matrix
        run: echo "Matrix values: ${{ matrix.param2 }}"