name: Matrix Example

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param1: [value1, value2, value3]
    steps:
      - name: Set Output
        id: set_output
        run: echo "::set-output name=matrix::value1,value2,value3"
      - name: Print Matrix
        run: |
          echo "Matrix values: ${{ matrix.param1 }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param2: ${{ steps.set_output.outputs.matrix }}
    steps:
      - name: Print Matrix
        run: |
          echo "Matrix values: ${{ matrix.param2 }}"