name: Indirect Matrix Example

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{steps.changed-files.outputs.all_changed_files}}
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f
        with:
          files: apps
          dir_names: "true"
          dir_names_max_depth: 0
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print Matrix
        run: |
          echo "Matrix values: ${{ (needs.job1.outputs.matrix }}"


