name: Indirect Matrix Example

on:
  push:
    branches: [ "*dev" ]
  pull_request:
    branches: [ "*dev" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:  
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@b2d17f51244a144849c6b37a3a6791b98a51d86f
      with:
            files: apps
            dir_names: "true"
            dir_names_max_depth: 2
    - name: Set matrix
      id: set-matrix
      run: |
         echo "matrix=[${{steps.changed-files.outputs.all_changed_files}}]" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        param2: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - name: Print Matrix
        run: |
          echo ${{ matrix.param2}}


